name: deploy-mkdocs site 

on:
  push:
    branches: [ master ]
    paths-ignore:
       - '.github/workflows/*.yml'
  pull_request:
    branches: [ master ]
    paths-ignore:
       - '.github/workflows/*.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install mkdocs-material mkdocs-literate-nav mkdocs-gen-files
      - run: mkdocs gh-deploy --force
